SELECT * FROM PLAYER ;
SELECT * FROM PLAYER_QUESTION ;
SELECT * FROM QUESTION ;
SELECT * FROM STORE ;
SELECT * FROM STORE_LOG ;

CREATE TABLE PLAYER ( PLAYER_ID VARCHAR2(20) NOT NULL , 
PW1 VARCHAR2(20) NOT NULL , PW2 NUMBER(20) NOT NULL , 
POINT NUMBER(10) DEFAULT 0 , RANKING NUMBER(10) DEFAULT 0 ) ; 

INSERT INTO PLAYER VALUES ('test', '123', 12345, 0, 0) ;
INSERT INTO PLAYER VALUES ('test01', '123', 12345, 52, 10) ;
INSERT INTO PLAYER VALUES ('test02', '123', 12345, 10, 20) ;
INSERT INTO PLAYER VALUES ('test03', '123', 12345, 75, 30) ;
INSERT INTO PLAYER VALUES ('test04', '123', 12345, 90, 39) ;
INSERT INTO PLAYER VALUES ('test05', '123', 12345, 11, 20) ;
INSERT INTO PLAYER VALUES ('test06', '123', 12345, 25, 50) ;
INSERT INTO PLAYER VALUES ('test07', '123', 12345, 25, 370) ;
INSERT INTO PLAYER VALUES ('test08', '123', 12345, 25, 250) ;
INSERT INTO PLAYER VALUES ('test09', '123', 12345, 25, 310) ;
INSERT INTO PLAYER VALUES ('test10', '123', 12345, 25, 310) ;
INSERT INTO PLAYER VALUES ('수고했다', '999', 99999, 99, 9999) ;

DELETE PLAYER WHERE PLAYER_ID = 'test' ;
SELECT * FROM PLAYER ORDER BY PLAYER_ID DESC ;
COMMIT ;

SELECT * FROM PLAYER ORDER BY RANKING DESC ;
SELECT * FROM PLAYER ORDER BY RANKING ;
COMMIT ;
UPDATE PLAYER SET POINT = 13520 , RANKING = 137330 WHERE PLAYER_ID = '' ; 
UPDATE PLAYER SET POINT = 35 WHERE PLAYER_ID = '' ; 
UPDATE PLAYER SET pw1 = 123 , pw2 = 12345 WHERE PLAYER_ID = '' ; 

SELECT * 
  FROM (
        SELECT PLAYER_ID 
             , RANKING 
             , POINT 
          FROM PLAYER 
         ORDER BY RANKING DESC
         )
 WHERE ROWNUM <= 10 ;
 
SELECT A.PLAYER_ID
     , A.POINT
     , A.RANKING
     , B.ITEM_ID
     , B.ITEM_CNT
  FROM PLAYER A INNER JOIN STORE_LOG B 
    ON (A.PLAYER_ID = B.PLAYER_ID) 
   AND A.PLAYER_ID = '박현우' ;

SELECT ITEM_ID
     , SUM(ITEM_CNT)
  FROM STORE_LOG
 GROUP BY ITEM_ID
 ORDER BY ITEM_ID ;

SELECT DISTINCT A.PLAYER_ID AS 사용자이름
     , A.ITEM_ID AS 아이템이름
     , B.아이템합계
  FROM STORE_LOG A
  JOIN (
        SELECT ITEM_ID
             , SUM(ITEM_CNT) AS 아이템합계
          FROM STORE_LOG
         GROUP BY ITEM_ID
         ) B 
    ON A.ITEM_ID = B.ITEM_ID 
 ORDER BY A.PLAYER_ID ;
 
SELECT * FROM STORE ;

SELECT * FROM PLAYER ORDER BY 1 ;
SELECT * FROM STORE ;
SELECT * FROM STORE_LOG ;
COMMIT ;
INSERT INTO STORE_LOG VALUES ('test01' , '포인트증가3' , 20 , 10000 , SYSDATE ) ;
INSERT INTO STORE_LOG VALUES ('test01' , '포인트증가1' , -1 , 0 , SYSDATE ) ;
UPDATE STORE_LOG SET PRICE = 10000 WHERE PLAYER_ID = 'test01' AND ITEM_ID = '포인트증가3' ; 
DELETE FROM STORE_LOG WHERE PLAYER_ID = 'test01' AND ITEM_ID = '포인트증가1' AND PRICE = 0 ;
ROLLBACK ;

values (
'16', --QUESTION_NUMBER
'LOLTIMO', --TITLE
'티모', --ANSWER
'C:\Users\smhrd\Downloads\MiniProject_java-main\mp3\IronMan_edit.MP3',--PATH
'게임',--GENRE
'대사를 맞춰 주세요 = O OO O OO OOO', --EXPLICATION
'C:\Users\smhrd\Downloads\MiniProject_java-main\mp3\IronMan_or.MP3' --PATH2
);


