
-- DROP TABLE TB_TODO CASCADE CONSTRAINTS ;
-- DROP SEQUENCE tb_todo_SEQ; 
-- DROP TRIGGER tb_todo_SEQ; 

-- DROP TABLE TB_TODOCM CASCADE CONSTRAINTS ;
-- DROP SEQUENCE tb_todocm_SEQ; 
-- DROP TRIGGER tb_todocm_AI_TRG; 

-- DROP TABLE TB_TODORR CASCADE CONSTRAINTS ;
-- DROP SEQUENCE tb_todorr_SEQ; 
-- DROP TRIGGER tb_todorr_AI_TRG; 

-- 테이블 생성 SQL - tb_todo
CREATE TABLE tb_todo
(
    todo_seq        NUMBER(15, 0), 
    todo_id         VARCHAR2(30)    NOT NULL ,
    todo_content    VARCHAR2(4000)  DEFAULT '내용을 입력해 주세요~^*^', 
    todo_status     VARCHAR2(20)    DEFAULT 'false' , 
    todo_date       VARCHAR2(30)    DEFAULT SYSDATE , 
    PRIMARY KEY (todo_seq)
);

CREATE SEQUENCE tb_todo_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER tb_todo_AI_TRG
BEFORE INSERT ON tb_todo
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT tb_todo_SEQ.NEXTVAL
    INTO :NEW.tb_todo_seq
    FROM DUAL;
END;
/

-- 테이블 생성 TB_TODOCM 
CREATE TABLE TB_TODOCM 
(
  TODOCM_SEQ NUMBER(15, 0) 
, TODOCM_CONTENT VARCHAR2(4000) DEFAULT '^*^'
, TODOCM_STATUS VARCHAR2(20) DEFAULT 'true'
, TODOCM_DATE DATE DEFAULT SYSDATE 
, PRIMARY KEY (TODOCM_SEQ) 
);

CREATE SEQUENCE tb_todocm_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER tb_todocm_AI_TRG
BEFORE INSERT ON tb_todocm 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT tb_todocm_SEQ.NEXTVAL
    INTO :NEW.todocm_seq
    FROM DUAL;
END;
/

-- 테이블 생성 TB_TODORR
CREATE TABLE TB_TODORR 
(
  TODORR_SEQ NUMBER(15, 0) 
, TODORR_CONTENT VARCHAR2(4000) DEFAULT '^*^'
, TODORR_STATUS VARCHAR2(20) DEFAULT 'true'
, TODORR_DATE DATE DEFAULT SYSDATE 
, PRIMARY KEY (TODORR_SEQ) 
);

CREATE SEQUENCE tb_todorr_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER tb_todorr_AI_TRG
BEFORE INSERT ON tb_todorr 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT tb_todorr_SEQ.NEXTVAL
    INTO :NEW.todorr_seq
    FROM DUAL;
END;
/

COMMIT; 

COMMENT ON COLUMN TB_TODOCM.TODOCM_SEQ IS '응원글 순번';
COMMENT ON COLUMN TB_TODOCM.TODOCM_CONTENT IS '응원글 내용';
COMMENT ON COLUMN TB_TODOCM.TODOCM_STATUS IS '응원글 상태';

SELECT * FROM TB_MEMBER ;
SELECT * FROM TB_CALENDAR ORDER BY CAL_SEQ DESC ;
SELECT * FROM TB_CHATTING ORDER BY CHAT_SEQ DESC ;
SELECT * FROM TB_ROOM ORDER BY ROOM_SEQ DESC;

SELECT * FROM TB_TODO ORDER BY TODO_SEQ DESC ;
SELECT * FROM TB_TODOCM ORDER BY TODOCM_SEQ ;
SELECT * FROM TB_TODORR ORDER BY TODORR_SEQ ;

delete from tb_member where mb_nick = '장재욱' ;
update tb_member set mb_nick = '장재욱' where mb_id = '장재욱' ;

update TB_TODO set TODO_CONTENT = 2
 where todo_seq = 445
   and todo_id = '장재욱' ;

select * from (
        select * from TB_TODOCM 
         order by dbms_random.random
            ) 
 where rownum <= 1 ;

DELETE FROM TB_TODO ;

COMMIT ;

SELECT * FROM TB_TODO ORDER BY TODO_SEQ DESC ;

DECLARE
    TODO_STATUS VARCHAR2(10) ;
    BEGIN
        SELECT TODO_STATUS INTO TODO_STATUS FROM TB_TODO WHERE TODO_SEQ = 221 ;
		IF TODO_STATUS = 'false' THEN
			update TB_TODO set TODO_STATUS = 'true' where TODO_SEQ = 221 ;
		ELSE
			update TB_TODO set TODO_STATUS = 'false' where TODO_SEQ = 221 ;
		END IF ;
    END ;
/

update TB_TODO set TODO_STATUS = 'false' where TODO_SEQ = 221 ;
update TB_TODO set TODO_STATUS = 'true' where TODO_SEQ = 221 ;
update TB_TODO set TODO_SEQ = 277 - 1 where TODO_SEQ = 0 ;

ALTER TABLE TB_TODO MODIFY TODO_CONTENT DEFAULT '입력하세요 ^*^' ;
ALTER TABLE TB_TODO MODIFY TODO_STATUS DEFAULT 'false' ;
ALTER TABLE TB_TODO MODIFY TODO_COLOR DEFAULT 'white' ;
 
DELETE FROM TB_TODO ;
 
DELETE FROM TB_TODO
 WHERE TODO_SEQ = 239 ;
 
UPDATE TB_TODO
   SET TODO_STATUS = 'true'
 WHERE TODO_SEQ = 199 ;

insert into TB_TODO (
		TODO_CONTENT,
		TODO_STATUS,
		TODO_COLOR
		) values (
		'테스트',
		'테스트',
		'테스트'
		);
        
insert into TB_TODO (
		TODO_CONTENT
		) values (
		'테스트'
		);