SET DEFINE OFF

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 1', '채팅룸 1', '채팅내용 2');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 1', '채팅룸 1', '채팅내용 3');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 1', '채팅룸 1', '채팅내용 4');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 1', '채팅룸 1', '채팅내용 5');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 1', '채팅룸 2', '채팅내용 1');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 1', '채팅룸 2', '채팅내용 2');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 1', '채팅룸 2', '채팅내용 3');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 1', '채팅룸 2', '채팅내용 4');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 1', '채팅룸 2', '채팅내용 5');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 2', '채팅룸 1', '채팅내용 1');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 2', '채팅룸 1', '채팅내용 2');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 2', '채팅룸 1', '채팅내용 3');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 2', '채팅룸 1', '채팅내용 4');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 2', '채팅룸 1', '채팅내용 5');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 2', '채팅룸 2', '채팅내용 1');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 2', '채팅룸 2', '채팅내용 2');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 2', '채팅룸 2', '채팅내용 3');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 2', '채팅룸 2', '채팅내용 4');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 2', '채팅룸 2', '채팅내용 5');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 3', '채팅룸 1', '채팅내용 1');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 3', '채팅룸 1', '채팅내용 2');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 3', '채팅룸 1', '채팅내용 3');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 3', '채팅룸 1', '채팅내용 4');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 3', '채팅룸 1', '채팅내용 5');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 3', '채팅룸 2', '채팅내용 1');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 3', '채팅룸 2', '채팅내용 2');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 3', '채팅룸 2', '채팅내용 3');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 3', '채팅룸 2', '채팅내용 4');

INSERT INTO TB_CHAT (CHAT_ID, CHAT_ROOM_ID, CHAT_CONTENT) 
VALUES ('아이디 3', '채팅룸 2', '채팅내용 5');

