SET DEFINE OFF

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('1. 당신의 이름은 무엇인가요? 어떤뜻이에요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('2. 아침에 일어나서 제일 먼저 하는 일?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('3. 바닥에서 자는 걸 좋아해요? 침대에서 자는 걸 좋아해요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('4. 가족이랑 같이 사나요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('5. 집에서 가장 좋아하는 공간은 어디예요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('6. 학교와 집은 얼마나 먼가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('7. 통학 시간엔 뭘 해요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('8. 세상에서 제일 사랑하는 사람은 누군가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('9. 이제 곧 크리스마스인데, 계획 있어요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('10. 크리스마스 말고 1년 중 가장 좋아하는 날은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('11. 생일은 언제예요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('12. 어떤 태몽과 함께 태어났나요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('13. 돌잔치에서 뭐 집었어요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('14. 초딩 때 꿈은 뭐였나요? 지금은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('15. 초딩 때 꿈을 지금도 꾸고 있나요? (^*^)');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('16. 타임머신이 있다면 언제로 가고싶어요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('17. 부지런한 편인가요? (^*^)');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('18. 자신만의 시간 보내는 비법이 있다면?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('19. 남들에게 말하고 싶은 ‘플렉싱’이 있나요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('20. 드라마 좋아해요? 무슨 작품?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('21. 제일 좋아하는 작가는?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('22. 남친/여친 삼고 싶은 연예인을 꼽는다면?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('23. 요즘 즐겨 보는 프로그램은 뭐예요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('24. 무한도전 멤버 중 제일 좋아하는 사람은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('25. 카카오프렌즈 중 최애는 누구?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('26. 겨울만 되면 생각나는 노래가 있다면?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('27. 가장 최근에 가본 콘서트?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('28. 목소리가 굵은 편? 얇은 편?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('29. 노래방가면 자주 부르는 노래는?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('30. 좋아하지만 잘 못 부르는 노래는?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('31. 요즘 제일 꽂힌 곡은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('32. 다시 태어나면 뭘로 태어나고 싶어요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('33. 발 사이즈가 어떻게 돼요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('34. 가장 아끼는 신발은 뭐예요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('35. 요즘 제일 사고 싶은 것?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('36. 당신을 물욕에 빠트리는 가장 큰 요인은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('37. 로또 당첨되면 뭐 할래요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('38. 지금 통장 잔고는?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('39. 알바 해봤어요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('40. 잊을 수 없는 알바 에피소드가 있나요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('41. 가장 최근에 사귄 친구는 누군가요? 어떻게 친구가 됐어요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('42. 친구랑 가장 가고싶은 곳은? (^*^)');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('43. 외계인이 지배하는 세상이 온다면 당신은 뭘 할 수 있을까요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('44. 외계인하고 어떤 얘기 하고 싶어요? (^*^)');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('45. 자주 가는 단골 가게가 있나요? 꼭 시켜 먹는 메뉴는?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('46. 어디에서 어떤 음식 먹는걸 좋아해요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('47. 나중에 장사를 한다면 어떤 가게를 차리고 싶어요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('48. 요리 잘해요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('49. ‘이거 하난 자신 있다’ 하는 음식은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('50. 제일 좋아하는 라면은 뭔가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('51. 주종은? 소주? 맥주? 와인? 소맥?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('52. 주량은 어떻게 돼요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('53. 가장 즐거운 술자리 모임을 꼽는다면?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('54. 살면서 가장 슬펐던 적은 언제예요? 어떻게 극복했나요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('55. 인생의 롤 모델이 있나요? 누군가요? 그 이유는?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('56. 가장 가고 싶은 여행지는? (^*^)');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('57. 당신은 친구들에게 어떤 사람이라고 평가 받나요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('58. 부모님이 당신에게 가장 자주 하시는 말은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('59. 살면서 행한 배려 중 가장 센 것은 뭔가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('60. 전공이 뭐예요? 왜 그 공부를 했어요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('61. 전공이 좋은 이유는? (^*^)');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('62. 지금껏 들어본 수업 중 가장 재밌었던 수업은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('63. 가장 최고였던 교수님은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('64. 시험 기간에 자주 하는 행동은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('65. 좋아하는 동물 있어요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('66. 당신을 동물에 비유하자면 무엇일까요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('67. 가장 최근에 본 영화?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('68. 좋아하는 감독은 누구인가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('69. 요즘의 고민은 뭔가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('70. 고민이 있을 때, 혼자서 생각한다. 여럿에게 조언을 구한다.');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('71. 제일 듣고싶은 말은? (^*^)');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('72. 스스로 한심하게 여겨질 때는 언젠가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('73. 몇 번의 연애를 해봤나요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('74. 한 사람의 기억만 간직할 수 있다면?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('75. 연애를 길게 하는 편인가요? 짧게하는 편인가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('76. 당신은 장거리 연애가 가능한 사람인가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('77. 연인의 어떤 행동이 당신을 제일 행복하게 만드나요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('78. 외로움을 해소하는 나만의 방법은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('79. 당신의 ‘리즈 시절’은 언제인가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('80. 자신감을 넘치게 해주는 아이템은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('81. 사연 있는 옷이 있나요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('82. 삶을 풍요롭게 하는 자신만의 ‘의식’이 있나요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('83. SNS 많이 해요? 즐겨 염탐하는 계정은? 그 계정을 탐독하는 이유는?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('84. 여행가서 사진 찍은적 있나요? (^*^)');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('85. SNS에 사진 올릴 때 제일 신경쓰는 점은?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('86. 스스로 가장 바꾸고 싶은 점이 있다면?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('87. 영원히 간직하고 싶은 장점은요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('88. 최근 누군가를 사랑했던 적 있나요? (^*^)');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('89. 스트레스 푸는 방법?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('90. 가끔 생각나는 ‘문장’이 있나요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('91. 약속을 잘 지키는 편인가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('92. 살면서 자신과의 약속을 딱 하나 정한다면?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('93. 지금 당장 보고 싶은 사람? 그 사람에게 지금 카톡을 보낸다면 뭐라고 쓸 건가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('94. 자기 전에 꼭 하는 일?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('95. 가장 행복하게 잠들었던 밤은 언젠가요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('96. 잠 안 오는 날 어떻게 해요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('97. 깨고 싶지 않았던 꿈?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('98. 오늘 하루를 한 줄로 요약한다면?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('99. 내일은 어떤 하루였으면 좋겠어요?');

INSERT INTO TB_TODORR (TODORR_CONTENT) 
VALUES ('100. 꼭 성공하세요~!!! (^*^)');

